version: '3.8'


services:
  postgres:
    image: postgres:latest
    container_name: body-density-calculator-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: body-density-calculator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678